Allow gotcha to run as a cf app
starkandwayne/gotcha pull request #3
Opened 2016-10-26 18:57 UTC by geofffranks

`gotcha` can now run as a Cloud Foundry app. It pulls
`PORT` from the environment to determine what to bind to,
and its target from the `GOTCHA_BACKEND` environment variable.

The `PORT` env var is only used if no ports are explicitly
configured via the CLI invocation of `gotcha`. If neither
CLI args nor `PORT` env var exists, fails back to port 3128.

The `GOTCHA_BACKEND` env var is only used when there are no
CLI args to gotcha at all. Otherwise, the behavior is the same
as it previously was.

Additionally, the `SSL_SKIP_VERIFY` environment variable
can be used to disable SSL certificate checking of the
backend gotcha is hooked up to.

And for kicks, the HTTP_PROXY/HTTPS_PROXY/NO_PROXY env
vars are now also supported

2016-10-27 14:39 UTC, jhunt requested changes
I like it, overall, just needs some minor polishing

2016-10-27 14:39 UTC, jhunt commented on main.go
> +		}
This is a lot of code duplication.  Can we set a target based on flags / environment, and only parse / check it the one time?

2016-10-27 14:39 UTC, jhunt commented on main.go
> +		target, err = url.Parse(os.Getenv("GOTCHA_BACKEND"))
What happens here if we run the command without arguments, but _don't_ specify the `GOTCHA_BACKEND` environment variable?

I would like to see a more helpful error message like:
> No backend host specified, and no $GOTCHA_BACKEND environment variable set
> If you are deploying gotcha as a Cloud Foundry application, don't forget to `cf set-env appname GOTCHA_BACKEND https://host/url

That way, when I forget how to use this, the tools tell me what I done forgot.

2016-10-27 15:01 UTC, geofffranks commented
Changes provided

2016-10-28 01:31 UTC, jhunt approved these changes
:+1:

2016-10-28 01:31 UTC, merged